- good-buy-frontend/src/pages/shoppingList/index.jsx
Functionality is the exact same, no new implementation, just ground work laid for new implementation.
> Functions + Multiple Checkboxes

- good-buy-frontend/src/pages/shoppingCart/cart.json
- good-buy-frontend/src/pages/shoppingCart/index.jsx
> Shopping cart page UI

- good-buy-frontend/src/pages/shoppingList/WIP.txt
> Work in progress.

- good-buy-backend/data-scripts/jsonwithdumps.py
Images, brand, category, stock, clearance
> Updated data script

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Updated the body responses of the each call but still working on creating unit test for this lambda function.
> Updated the body responses

- good-buy-frontend/aws setup.txt
its a txt file, needs to get implemented
> AWS setup for react

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Needed to add a pylint ignore message for the lambda context variable since it is not used within my function call, but lambda requires me to keep this variable inorder for the function to work.
> Needed to add a pylint ignore message for lambda context variable

- good-buy-backend/good-buy-dynamodb-handler/requirements.txt
- good-buy-backend/good-buy-dynamodb-handler/tests/test_lambda_function.py
- requirements.txt
Created a unit test for DynamoDB lambda function.
> Dynamodb unittest

- good-buy-backend/good-buy-dynamodb-handler/tests/test_lambda_function.py
Created test_lambda_post_user() function for dynamodb unittest. Tests post functionality to dynamodb table.
> Created test_lambda_post_user() function for dynamodb unittest

- good-buy-backend/good-buy-dynamodb-handler/tests/test_lambda_function.py
Created test_lambda_delete_user() function to test delete functionality of DynamoDB lambda function.
> Created test_lambda_delete_user() function to test delete functionality

- good-buy-frontend/src/pages/shoppingCart/index.jsx
> add quantity to shoppping cart

- good-buy-frontend/src/pages/shoppingCart/index.jsx
> add two decimal places

- good-buy-frontend/src/App.js
- good-buy-frontend/src/components/products/SearchBar.jsx
- good-buy-frontend/src/pages/home/index.jsx
- good-buy-frontend/src/pages/products/index.jsx
- good-buy-frontend/src/utils/home/utils.js
- good-buy-frontend/src/utils/products/utils.js
Removed a lastSearchItem name from the filters array and put it as a separate key in a state. Updated the useEffect hook calls of Home and Products pages.
> Fixed search product by name functionality.

- good-buy-backend/data-scripts/addToCart.py
uses user email, file address, and dict of a product
> ADD TO A SHOPPING CART

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
I have to refactor how we are adding a product to a shopping cart. I was using Copper's function but I don't think that I can use it because it creates a local JSON file when it is run. I do not think that lambda allows for this to happen so I am trying to incorporate this functionality a different way.
> Refactoring add to cart functionality

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
had to revert back to previous version of dynamodb lambda without the use of Cooper's addToCart function. Was not working as expected.
> Reverting to previous iteration of lambda

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Had to refactor to use the tempfile package in Python to create temporary files for appending new products to a cart in the DynamoDB lambda function.
> Used tempfile package to create temp files

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Fixed the format of the cart value in DynamoDB when a new product is added to a user's cart.
> Fixed the formatting for DynamoDB cart value

- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Added Cooper's functionality of creating a new cart when a user is created.
> Generate user cart

- good-buy-backend/good-buy-dynamodb-handler/README.md
- good-buy-backend/good-buy-dynamodb-handler/lambda_function.py
Added the functionality to be able to remove an item from a user's cart.
> Added functionality to remove item from cart
